modLoader = "javafml"
loaderVersion = "[${neoforge_loader_version},)"
license = "All Rights Reserved"

[[mods]]
modId = "ftbbackups3"
version = "${version}"
displayName = "FTB Backups 3"
displayURL = "https://www.curseforge.com/minecraft/mc-mods/ftb-backups"
logoFile = "logo.png"
authors = "FTB Team"
description = '''
Creates backups of your world
'''

[[dependencies.ftbbackups3]]
modId = "neoforge"
mandatory = true
versionRange = "${neoforge_version_range}"
ordering = "NONE"
side="BOTH"

[[dependencies.ftbbackups3]]
modId = "ftblibrary"
type = "required"
versionRange = "${ftb_library_version_range}"
ordering = "AFTER"
side = "BOTH"

[[dependencies.ftbbackups3]]
modId = "minecraft"
type = "required"
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"
